name: CI

on:
  [push, pull_request]

env:
  CI_REPO_NAME: ${{ github.repository }}
  CI_COMMIT_ID: ${{ github.sha }}

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      NODE_VERSION: ${{steps.engines.outputs.NODE_VERSION}}
      CACHE_KEY: ${{steps.cache.outputs.CACHE_KEY}}
    steps:
      - uses: actions/checkout@v2

      - name: Set Node version
        id: engines
        run: |
          echo "::set-output name=NODE_VERSION::$(jq -r '.engines.node' package.json)"

  tests:
    runs-on: ubuntu-latest
    needs:
      - init
    strategy:
      matrix:
        script: [ 'test' ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "${{ needs.init.outputs.NODE_VERSION }}"
      - name: Install Packages
        run: |
          npm ci
      - name: Run unit ${{ matrix.script }}
        run: npm run ${{ matrix.script }}

  deploy-staging:
    if: github.ref == 'refs/heads/main'
    needs:
      - init
      - tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#       - uses: actions/checkout@v2
#       - uses: go-semantic-release/action@v1
#       - uses: actions/setup-node@v1
#         with:
#           node-version: "${{ needs.init.outputs.NODE_VERSION }}"
#           github-token: ${{ secrets.GH_TOKEN }}
#           update-file: package.json
#       - name: Install Packages
#         run: |
#           npm ci
      - name: build
        run:  echo "Stage release"

