name: release-tag

on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published, created, edited]

env:
  CI_REPO_NAME: ${{ github.repository }}
  CI_COMMIT_ID: ${{ github.sha }}

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      NODE_VERSION: ${{steps.engines.outputs.NODE_VERSION}}
      CACHE_KEY: ${{steps.cache.outputs.CACHE_KEY}}
    steps:
      - uses: actions/checkout@v2

      - name: Set Node version
        id: engines
        run: |
          echo "::set-output name=NODE_VERSION::$(jq -r '.engines.node' package.json)"
  tests:
    runs-on: ubuntu-latest
    needs:
      - init
    strategy:
      matrix:
        script: [ 'test' ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "${{ needs.init.outputs.NODE_VERSION }}"
      - name: Install Packages
        run: |
          npm ci
      - name: Run unit ${{ matrix.script }}
        run: npm run ${{ matrix.script }}

  deploy-prod:
    needs:
      - init
      - tests
    runs-on: ubuntu-latest
    steps:
       - run: echo "prod"
