name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Revision'
        required: true
        default: ''

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
       if curl --fail ${{ REDIRECTOR_ROUTE }} -X PUT \
         -d '{ "name":"${{ PACKAGE_NAME }}", "revision":"latest", "target": "${{ REDIRECTOR_TARGET }}/${{ PACKAGE_NAME }}/${{ github.event.inputs.revision }}" }' \
         -H "Content-Type: application/json" \
         -H "x-auth: ${{ REDIRECTOR_SECRET }}"; then
         echo "Successful rollback, new revision: ${{revision}}"
       else
        echo "Rolback was unsuccessful!"
        exit 1
       fi;

